AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create_items/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events: 
        CreateItem:
          Type: Api
          Properties:
            Path: /items
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
  
  ListItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/return_items/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        ListProduct:
          Type: Api
          Properties:
            Path: /items
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable

  UpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/update_items/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events: 
        CreateItem:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: put
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ItemsTable


  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Items"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

Outputs:
  ItemApi:
      Description: "API Gateway Items Endpoint"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"